### ISSUE TITLE
Timing data

### ISSUE THREAD

**Issue by andersy005** [NCAR/cesm-lens-zarrification#1]
@kmpaul,  I have a quick question regarding the throughput calculation. For time spent, I am using `user+sys` as the total time, or should I use `real` instead?

```bash
abanihi@cheyenne2: /glade/scratch/abanihi/data $ time aws s3 cp --recursive AWS/ s3://zarr-test-bucket --quiet

real    22m5.465s
user    14m26.092s
sys     1m46.620s
```

**Comment by kmpaul** [comment]
You should use `real`, but `real` includes "wait" times when the system is blocking for some reason or another.  However, those wait times are real, and you need to include them.  However, you might run the command many (10?) times and record the average and spread of the times.

**Comment by andersy005** [comment]
Got you! I will record as many transfers as I can, and update the numbers. The accelerate feature I was telling you about, doesn't look promising for the region (Oregon (US-WEST-2)) our bucket is in. Here are the [speed test results](http://s3-accelerate-speedtest.s3-accelerate.amazonaws.com/en/accelerate-speed-comparsion.html?result=1477-2386-07069-05215&identityId=unknown).
