### ISSUE TITLE
Create zarrification notebook for NA-CORDEX

### ISSUE THREAD

**Issue by bonnland** [NCAR/cesm-lens-zarrification#8]
I am in the process of creating a notebook based on zarrify.ipynb for the LENS data.   It will include slightly different steps, including alignment of datasets using different calendars.

**Comment by andersy005** [comment]
You may want to look at the latest version of `zarrify.ipynb` notebook on the master branch. I added some helper function for fixing the time coordinate. You may be able to easily adapt it to your calendar conversion need.

**Comment by bonnland** [comment]
I think I could use a quick lesson from you on how to navigate through these notebooks to understand the code.   I am trying to use Jupyter Lab to step through, but it is very slow.   If it helps, I can load the IDE you are using and we can step through the notebook together?  I am just not feeling very productive catching up with what you have written so far.   Thanks...

**Comment by bonnland** [comment]
Closed by #10
